# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Coding_Issues.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1008, 535)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.token_input = QtWidgets.QLineEdit(Form)
        self.token_input.setMouseTracking(True)
        self.token_input.setTabletTracking(False)
        self.token_input.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.token_input.setObjectName("token_input")
        self.horizontalLayout.addWidget(self.token_input)
        self.qurey_button = QtWidgets.QPushButton(Form)
        self.qurey_button.setObjectName("qurey_button")
        self.horizontalLayout.addWidget(self.qurey_button)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.line = QtWidgets.QFrame(Form)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.output = QtWidgets.QTabWidget(Form)
        self.output.setObjectName("output")
        self.resule_tab = QtWidgets.QWidget()
        self.resule_tab.setObjectName("resule_tab")
        self.gridLayout = QtWidgets.QGridLayout(self.resule_tab)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.textBrowser = QtWidgets.QTextBrowser(self.resule_tab)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout_2.addWidget(self.textBrowser)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.output.addTab(self.resule_tab, "")
        self.raw_tab = QtWidgets.QWidget()
        self.raw_tab.setObjectName("raw_tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.raw_tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.raw_tab)
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.gridLayout_2.addWidget(self.textBrowser_2, 0, 0, 1, 1)
        self.output.addTab(self.raw_tab, "")
        self.verticalLayout.addWidget(self.output)
        self.horizontalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Form)
        self.output.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Coding_Issues"))
        self.token_input.setText(_translate("Form", "Pleace Copy Your Bearer Token Here."))
        self.qurey_button.setText(_translate("Form", "query"))
        self.output.setTabText(self.output.indexOf(self.resule_tab), _translate("Form", "Result"))
        self.output.setTabText(self.output.indexOf(self.raw_tab), _translate("Form", "Raw"))
